# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/escar/OneDrive/Documentos/GitHub/TFG/Vivado/zedboard-imageProcessing/zedboard-imageProcessing.srcs/sources_1/ip/outputBuffer/outputBuffer.xci
# IP: The module: 'outputBuffer' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/escar/OneDrive/Documentos/GitHub/TFG/Vivado/zedboard-imageProcessing/zedboard-imageProcessing.gen/sources_1/ip/outputBuffer/outputBuffer.xdc
# XDC: The top module name and the constraint reference have the same name: 'outputBuffer'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/escar/OneDrive/Documentos/GitHub/TFG/Vivado/zedboard-imageProcessing/zedboard-imageProcessing.gen/sources_1/ip/outputBuffer/outputBuffer_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'outputBuffer'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Users/escar/OneDrive/Documentos/GitHub/TFG/Vivado/zedboard-imageProcessing/zedboard-imageProcessing.srcs/sources_1/ip/outputBuffer/outputBuffer.xci
# IP: The module: 'outputBuffer' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/escar/OneDrive/Documentos/GitHub/TFG/Vivado/zedboard-imageProcessing/zedboard-imageProcessing.gen/sources_1/ip/outputBuffer/outputBuffer.xdc
# XDC: The top module name and the constraint reference have the same name: 'outputBuffer'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/escar/OneDrive/Documentos/GitHub/TFG/Vivado/zedboard-imageProcessing/zedboard-imageProcessing.gen/sources_1/ip/outputBuffer/outputBuffer_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'outputBuffer'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
